name=ESPNOW_Rimocon for ESP32
version=1.0
author=Tomoooji
maintainer=Tomoooji
sentence=library for making rimocon with esp-now
paragraph=Caution! cannot be used in ESP8266 and other esp device except ESP32
category=Device Control
architectures=*